### PR TITLE
fix(kble-socket): compile with features = ["stdio"] alone

### PR DESCRIPTION
**Pull request by sksat**
## What

Fixes a **pre-existing** feature-flag bug: `kble-socket` with `features = ["stdio"]` (without `tungstenite`) failed to compile.

## The bug

`lib.rs` re-exported `from_stdio` whenever `stdio` was enabled:
```rust
#[cfg(feature = "stdio")]
pub use stdio::{from_stdio, Stdio};
```
But `from_stdio` is `#[cfg(feature = "tungstenite")]` (it builds a `WebSocketStream`). So `stdio` alone gave `error[E0432]: unresolved import stdio::from_stdio`.

## Fix

Gate the `from_stdio` re-export on **both** features; `stdio` alone still provides the `Stdio` byte-stream adapter:
```rust
#[cfg(feature = "stdio")]
pub use stdio::Stdio;
#[cfg(all(feature = "stdio", feature = "tungstenite"))]
pub use stdio::from_stdio;
```

## Notes

- **Pre-existing**, unrelated to #189 (cancellable stdin). Split out per review so #189 stays focused; touches only `lib.rs`, so no conflict with #189.
- The kble plugs all enable `stdio` + `tungstenite`, so this changes nothing for them — it just unbreaks the `stdio`-only combo.
- Verified: `cargo build -p kble-socket --no-default-features --features stdio` and `--features stdio,tungstenite` both succeed; full `cargo test` green.
- Minor: a `stdio`-only build still emits an unused-import warning for `from_stdio`'s types (in `stdio.rs`); not hit in CI (which builds `stdio`+`tungstenite`), can be tidied alongside the `stdio.rs` changes.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by sksat** [comment]
The feature-powerset CI guard added in #191 correctly catches the bug this PR fixes.

Running #191's new `cargo hack check --feature-powerset` against `main` (i.e. *without* this fix), the `verify-crate` job fails at exactly the `stdio`-only combination:

```
running `cargo check --no-default-features --features stdio` on kble-socket (7/15)
error[E0432]: unresolved import `stdio::from_stdio`
   |
13 | pub use stdio::{from_stdio, Stdio};
   |                 ^^^^^^^^^^ no `from_stdio` in `stdio`
error: could not compile `kble-socket` (lib) due to 1 previous error
```

(run: https://github.com/arkedge/kble/actions/runs/26989996812/job/79647909232)

Every other step (clippy / fmt / `install cargo-hack`) passes; only the new `check feature powerset` step is red, on the single combination this PR repairs. Once this PR merges and #191 is rebased onto `main`, all 15 workspace feature combinations compile and #191 goes green — so #191 both *proves* and *guards against* this regression.
